module npc (PC, branch, zero, jump, Ext, jump_Addr, NPC);
    input      [31:0]  PC;

    input              branch;          // whether enter branch or not  
    input              zero;            // zero generated by ALU
    input              jump;            // whether jump or not

    input      [31:0]  Ext;             
    input      [25:0]  jump_Addr;       // instr[25:0] for j type op

    output reg [31:0]  NPC;

    always @(*)    
        if (branch && zero)
            NPC = (Ext << 2) + PC + 4; 
        else if (jump)              // different to P182, which jump iff jump == 0. Here, we do J op iff jump == 1
        begin    
            NPC = {PC[31:28], {jump_Addr[25:0] << 2}};
            // $display("jump!");
        end
        else
            NPC = PC + 4;

endmodule //npc 