module npc (PC, branch, zero, Jump, branch_Addr, jump_Addr, NPC, pc_add_out);
    input      [31: 0]  PC;

    input               branch;          // whether enter branch or not  
    input               zero;            // zero generated by ALU
    input               Jump;            // whether Jump or not

    input      [31: 0]  branch_Addr;             
    input      [25: 0]  jump_Addr;       // instr[25:0] for j type op

    output     [31: 0]  pc_add_out;      // pc + 4
    output reg [31: 0]  NPC;

    assign pc_add_out = PC + 4;

    always @(*)    
        if (branch && zero)
            NPC = branch_Addr; 
        else if (Jump)              // different to P182, which Jump iff Jump == 0. Here, we do J op iff Jump == 1
        begin    
            NPC = {PC[31:28], {jump_Addr[25:0] << 2}};
            // $display("Jump!");
        end
        else
            NPC = PC + 4;

endmodule //npc 